name: feature_profile
description: "Feature to insert, update and view user profile data."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../../common
  auto_route: ^9.2.2
  get_it: ^8.0.0
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  freezed: ^2.5.7
